### ISSUE TITLE
SpringMVC Sample AppをTomcat上で起動するときRun on Serverが出ない

### ISSUE THREAD

**Issue by shin-taro** [nabedge/mixer2-sample#10]
実行環境:Mac OS, STS  
http://mixer2.org/site/ja/springmvcsample.html にて
mixer2-fruitshop-springmvcプロジェクトをTomcat上で起動する
を進めようとしたところ、Run AsにRun on Serverが選択肢として表示されなかった。  
Run As > Run ConfigurationsからApache Tomcat > Tomcat v8.0 Server at localhost
でRunを一度実行したところビルドが行われ、
その後再度Run Asを開いたところRun on Serverが実行できるようになった。  
ドキュメントに記載されている
> プロジェクトを右クリック->Maven->UpdateProject

とは別のRun on Serverを実行出来るようにする方法にあたるかと思います。

**Comment by nabedge** [comment]
thank you ! https://github.com/nabedge/mixer2/commit/4b799f6dbeb3c01be8b29939caca82d0d6f2250d
Documentation on mixer2.org is to be rebuild for a few hours later.
