### ISSUE TITLE
UbuntuでのSTSのインストールについて

### ISSUE THREAD

**Issue by 5atk6** [nabedge/mixer2-sample#11]
## 概要
ドキュメント通りに操作してもUbuntu14.04でSTSを操作できない。

## 詳細
以下のページの「Spring Tool Suite (STS)」の章を参考にしてSTSを起動しても枠しか表示さず何も操作ができなかった。
http://mixer2.org/site/ja/DevelopmentEnvironment.html

## 再現手順
1. https://spring.io/tools より"3.6.4.RELEASE for linux"をダウンロード。
2. unzipコマンドでダウンロードしたzipファイルを解凍。
3. 解凍したフォルダにあるSTS(sts-bundle/sts-3.6.4.RELEASE/STS)を実行。
4. 起動はするが画面の枠しか表示されず何も操作できない。

## 期待する結果
Ubuntu(linux)におけるSTSのダウンロードから解凍、起動手順を以下のページに掲載して欲しい。
http://mixer2.org/site/ja/DevelopmentEnvironment.html

**Comment by nabedge** [comment]
thank you ! https://github.com/nabedge/mixer2/commit/4b799f6dbeb3c01be8b29939caca82d0d6f2250d
Documentation on mixer2.org is to be rebuild for a few hours later.
