### ISSUE TITLE
ダウンロード方法にちょっと詰まった（デザイン改善案）

### ISSUE THREAD

**Issue by yu1ro** [nabedge/mixer2-sample#13]
http://mixer2.org/site/ja/download.html

のページにおいて
インストール方法がMavenを用いる方法のみに見えてしまった
Mavenばかりが目立ってしまっており
jar file、zip archiveでのダウンロード方法を見逃してしまった。

それぞれのタイトルを目立つようにしてみました。
改善案↓↓

## jar file
http://search.maven.org/#search|ga|1|a%3A%22mixer2%22

## zip archive
http://mixer2.org/dist/

## maven dependency
```xml
<dependencies>
  <dependency>
    <groupId>org.mixer2</groupId>
    <artifactId>mixer2</artifactId>
    <version>x.x.x(set latest version on http://search.maven.org/#search|ga|1|a%3A%22mixer2%22 )</version>
  </dependency>
</dependencies>
```

**Comment by nabedge** [comment]
fixed. thanks yu1ro !
