### ISSUE TITLE
jarファイルの使い方とdependencyの意味について

### ISSUE THREAD

**Issue by gash717** [nabedge/mixer2-sample#14]
http://mixer2.org/site/ja/download.html
Downloadのページで, jarファイルをどのように扱うかが書かれていませんでした.
また, mavenのdependencyをどのように設定するのかが詳しく書いてありませんでした.

再現方法 :
> [Step1] [Download](http://mixer2.org/site/ja/download.html)のページへ飛ぶ.
> [Step2] jarファイルをダウンロードする.
> [Step3] dependencyの設定をしようとする.
> [Step4] 初心者に対する説明があまりなされていない.

期待すること :
> jarファイルをEclipseなどに取り込む方法まで書いてあること.
> dependencyについての説明が詳細に書いてあること.

**Comment by nabedge** [comment]
fixet in http://mixer2.org/site/helloworld.html . Thanks gashi717 !
