### ISSUE TITLE
Development Environmentにて、linuxでのSTSのインストール方法が書いてない 

### ISSUE THREAD

**Issue by yu1ro** [nabedge/mixer2-sample#16]
# 概要
http://mixer2.org/site/ja/DevelopmentEnvironment.html
のSTSのダウンロード方法がWindows用の方法しか書いてなかったので、
他のOSの用のインストール方法も欲しい。

linuxでは、インストーラーは使わない。

1. ダウンロードまでは同じ

2. 解凍
コマンドは
　```
　tar zxvf spring-tool-suite-X.X.X.RELEASE-eX.X.X-linux-gtk-x86_64.tar.gz
　```
3. 起動

sts-X.X.X.RELEASE/STS
を起動する。

**Comment by nabedge** [comment]
thank you ! https://github.com/nabedge/mixer2/commit/4b799f6dbeb3c01be8b29939caca82d0d6f2250d
Documentation on mixer2.org is to be rebuild for a few hours later.
