### ISSUE TITLE
Development Environmentにサンプルページへのリンクが欲しいです

### ISSUE THREAD

**Issue by yu1ro** [nabedge/mixer2-sample#18]
http://mixer2.org/site/ja/DevelopmentEnvironment.html
Development Environmentの最後まで進んだ場合に、
次にどこに進めばいいのかわからなかったので、

「サンプルページを動かしてみるならここ（リンク）を見てください」

みたいなのがあると嬉しいかもしれないです

**Comment by nabedge** [comment]
thank you ! https://github.com/nabedge/mixer2/commit/4b799f6dbeb3c01be8b29939caca82d0d6f2250d
