### ISSUE TITLE
mixer2-fruitshop-springbootの注文画面の配送先入力のエラーメッセージが無い

### ISSUE THREAD

**Issue by nabedge** [nabedge/mixer2-sample#20]
カートにいれた商品をチェックアウトして配送先を入力する画面で、
たとえば"your first name"を入れる欄を空欄にしておくと
hibernateのデフォルトのエラーメッセージが出るだけ。
もっと親切なメッセージにするべき

**Comment by NakanoMizuki** [comment]
mixer2-fruitshop-springbootサンプルにおいて、配送先フォームの入力がない場合に出力されるエラーメッセージを修正しました。
https://github.com/nabedge/mixer2-sample/commit/295a885cee0646cb1f171c22b94ba27b891f2520

画面出力は以下のように変更されます。
>修正前
>![2015-07-11 11 49 03](https://cloud.githubusercontent.com/assets/7775726/8632398/6eb50cce-27d4-11e5-9ab3-420eda098024.png)

>修正後
>![2015-07-11 11 26 05](https://cloud.githubusercontent.com/assets/7775726/8632395/65d806ce-27d4-11e5-9f4d-2bae86b65098.png)

この修正だと、テンプレートのhtmlのクラス名を取得して表示しているため、入力欄と差異が出てしまっています。 (例：Your first name に対して、Pleas input firsName)
htmlのクラス名を変更するか、クラス名を出さない(例：Please input)か、２通りの修正が考えられると思うのですが、どうでしょうか？

**Comment by NakanoMizuki** [comment]
プルリクエストを送りました。
https://github.com/nabedge/mixer2-sample/pull/26
