### ISSUE TITLE
how does this launch

### ISSUE THREAD

**Issue by ph-hs** [nabedge/mixer2-sample#28]
mvn jetty:run ?

mvn tomcat:run

the readme is not very detailed :-(

**Comment by nabedge** [comment]
Welcome! Thank you for your question!

Please see http://mixer2.org/site/springmvcsample.html

This "mixer2-sample" repository has several application.
The easist one is "mixer2-flowershop-springboot" that has  
"public static void main(String[] args)" method.

**Comment by nabedge** [comment]
OK. I have edited the readme. Thank you !
https://github.com/nabedge/mixer2-sample/blob/master/README.md
