### ISSUE TITLE
mixer2-fruitshop-springmvcプロジェクトをTomcat上で起動できない

### ISSUE THREAD

**Issue by ramesses2nd** [nabedge/mixer2-sample#3]
### 概要
[ドキュメント](http://mixer2.org/site/ja/springmvcsample.html)に従っても、サンプルプロジェクトをTomcat上で起動できない。

### 原因
ファイル-新規-その他からサーバを選択し、サーバプロジェクトを作成。サーバプロジェクト内のserver.xmlにサンプルプロジェクトを登録する必要がある。

**Comment by nabedge** [comment]
thank you ! https://github.com/nabedge/mixer2/commit/4b799f6dbeb3c01be8b29939caca82d0d6f2250d
Documentation on mixer2.org is to be rebuild for a few hours later.
