### ISSUE TITLE
Spring Tool SuiteのリンクがGoogleまでで止まっている

### ISSUE THREAD

**Issue by gash717** [nabedge/mixer2-sample#6]
http://mixer2.org/site/ja/DevelopmentEnvironment.html
以下の文のSpring Tool Suiteのリンクが, Googleの用語検索までで止まっています.

事実 :
> Spring Tool Suiteの公式サイトでいつでもダウンロード可能です。無償ですが、ユーザー登録が必要です。

期待すること : Spring Tool Suiteをクリックすると, 公式サイトにジャンプする.

**Comment by nabedge** [comment]
thank you ! https://github.com/nabedge/mixer2/commit/4b799f6dbeb3c01be8b29939caca82d0d6f2250d
Documentation on mixer2.org is to be rebuild for a few hours later.
