### ISSUE TITLE
環境構築におけるEclipseやIntelliJなどメジャーなIDEへの対応

### ISSUE THREAD

**Issue by ramesses2nd** [nabedge/mixer2-sample#7]
### 現状
ドキュメントの*Develop Environment*では、Java開発の初心者のためにSTSをベースに環境構築の方法が説明されています。

### 問題点

> STSをおすすめする理由
STSはSpringSourceが開発している eclipseベースのIDEで、無償で公開されています。 ノーマルのeclipseを使う場合はm2e(ビルドツールのmavenと連携するプラグイン）や WTP（Tomcat等のコンテナと連携するプラグイン）などを別にダウンロードして追加する必要がありますが、 STSではそれらがはじめから搭載済みの状態であるため、 結果として開発環境の準備が非常に簡単です。
逆に、もしもあなたが自分でeclipseやその他の開発環境を整えて 必要なプラグインを自分でチョイスすることができるなら、このドキュメントに頼る必要はありません。

とありますが、Mixer2を使用したい初心者はすでにJavaの環境は導入していると思います。初心者向けの開発環境構築記事などでは、EclipseやIntelliJといったIDEをベースに説明しているものがほとんどです。そのため、これらメジャーなIDEをベースに環境構築の説明を行った方が初心者には適していると思います。

### 改善案
EclipseやIntelliJなどIDEを使用しているのは前提として、プラグインの導入方法を説明するのが良いかと思います。

**Comment by nabedge** [comment]
thank you ! https://github.com/nabedge/mixer2/commit/4b799f6dbeb3c01be8b29939caca82d0d6f2250d
Documentation on mixer2.org is to be rebuild for a few hours later.
