### ISSUE TITLE
MacでのSTSインストール

### ISSUE THREAD

**Issue by shin-taro** [nabedge/mixer2-sample#8]
実行環境:Mac OS  
http://mixer2.org/site/ja/DevelopmentEnvironment.html に従って
MacでSTSをインストールしたところ、
インストーラは使わずzipファイルをダウンロードする形式であったため、
プロダクト選択画面がなかった。  
そのためMavenを選択するという手順がなく、
Mavenがデフォルトでインストールされていることがわからなかった。  
したがって、MacでのSTSのインストールではインストーラのプロダクト選択画面はなく、
Mavenがデフォルトでインストールされているということを説明したほうが良いと考えられる。

**Comment by nabedge** [comment]
thank you ! https://github.com/nabedge/mixer2/commit/4b799f6dbeb3c01be8b29939caca82d0d6f2250d
Documentation on mixer2.org is to be rebuild for a few hours later.
