### ISSUE TITLE
設定の画面が余分にある

### ISSUE THREAD

**Issue by gash717** [nabedge/mixer2-sample#9]
http://mixer2.org/site/ja/DevelopmentEnvironment.html
上記の通りにSTSを用いて作った際, 以下の文に続く画面が出てきませんでした.

事実 :
> 続いて、ApacheTomcatを選択します。バージョンは先ほどインストールしておいたTomcatに あわせて選択してください。create a new local serverのチェックボックスをオン にしてNextボタンを押します。

環境 :
> OSが上記のリンクではWindows, 自分の環境OS X Yosemite 10.10.2（14C1514）
> リンクでは, 2013年5月時点のSTSです. 今回は3.6.4.RELEASEを使いました.
> 実行した日時は2015年6月27日です.

STSをダウンロードしたページ :
> http://spring.io/tools/sts/all/
> 上記のページで, Mac用のものをインストールしました.

**Comment by nabedge** [comment]
thank you ! https://github.com/nabedge/mixer2/commit/4b799f6dbeb3c01be8b29939caca82d0d6f2250d
Documentation on mixer2.org is to be rebuild for a few hours later.
